# Generated by Django 2.1.7 on 2021-03-25 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20210325_1539'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['orderBAD']},
        ),
        migrations.RenameField(
            model_name='module',
            old_name='order',
            new_name='orderBAD',
        ),
    ]
