# Generated by Django 2.1.7 on 2021-03-25 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20210325_1554'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['order']},
        ),
        migrations.RenameField(
            model_name='module',
            old_name='orderBAD',
            new_name='order',
        ),
    ]
